# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

# Position Controllers ---------------------------------------
joint1_position_controller:
  type: position_controllers/JointPositionController
  joint: base_link__link_01
  pid: {p: 2000.0, i: 100, d: 500.0}
joint2_position_controller:
  type: position_controllers/JointPositionController
  joint: link_01__link_02
  pid: {p: 50000.0, i: 100, d: 2000.0}
joint3_position_controller:
  type: position_controllers/JointPositionController
  joint: link_02__link_03
  pid: {p: 20000.0, i: 50, d: 1000.0}
joint4_position_controller:
  type: position_controllers/JointPositionController
  joint: link_03__grapple
  pid: {p: 2000.0, i: 50, d: 200.0}
joint5_position_controller:
  type: position_controllers/JointPositionController
  joint: finger_joint1
  pid: {p: 2000.0, i: 50, d: 200.0}
joint6_position_controller:
  type: position_controllers/JointPositionController
  joint: finger_joint2
  pid: {p: 2000.0, i: 50, d: 200.0}
joint7_position_controller:
  type: position_controllers/JointPositionController
  joint: finger_joint3
  pid: {p: 2000.0, i: 50, d: 200.0}
joint8_position_controller:
  type: position_controllers/JointPositionController
  joint: finger_joint4
  pid: {p: 2000.0, i: 50, d: 200.0}

  