mrm:
  joint_state_controller:
   type: joint_state_controller/JointStateController
   publish_rate: 50

  mrm_joint_controller:
   type: position_controllers/JointTrajectoryController
   joints:
      - base_link__link_01
      - link_01__link_02
      - link_02__link_03
      - link_03__grapple

   constraints:
        goal_time: 0.6
        stopped_velocity_tolerence: 10
        base_link__link_01:   {trajectory: 0.1, goal: 0.1}
        link_01__link_02:     {trajectory: 0.1, goal: 0.1}
        link_02__link_03:     {trajectory: 0.1, goal: 0.1}
        link_03__grapple:     {trajectory: 0.1, goal: 0.1}

   stop_trajectory_duration: 0.5
   state_publish_rate:  50
   action_monitor_rate: 10
 

  gripper_controller:
   type: position_controllers/JointTrajectoryController
   joints:
      - finger_joint1
      - finger_joint2
      - finger_joint3
      - finger_joint4

   constraints:
        goal_time: 0.6
        stopped_velocity_tolerance: 10
        finger_joint1:   {trajectory: 0.1, goal: 0.1}
        finger_joint2:   {trajectory: 0.1, goal: 0.1}  
        finger_joint3:   {trajectory: 0.1, goal: 0.1}
        finger_joint4:   {trajectory: 0.1, goal: 0.1} 
  
   stop_trajectory_duration: 0.5
   state_publish_rate:  50
   action_monitor_rate: 10
 
   
 # Tune the pid parameters if want to use pid controller""
 # gazebo_ros_control/pid_gains:
                       
#   finger_joint1: {p: 100,  d: 50, i: 1, i_clamp: 1}
  #   finger_joint2: {p: 100,  d: 50, i: 1, i_clamp: 1}
  #   finger_joint3: {p: 100,  d: 50, i: 1, i_clamp: 1}
  #   finger_joint4: {p: 100,  d: 50, i: 1, i_clamp: 1}

  #   base_link__link_01: {p: 100,  d: 1, i: 1, i_clamp: 1}
  #   link_01__link_02:  {p: 100,  d: 1, i: 1, i_clamp: 1}
  #   link_02__link_03:  {p: 100,  d: 1, i: 1, i_clamp: 1}
 #    link_03__grapple:  {p: 100,  d: 1, i: 1, i_clamp: 1}