controller_list:
 - name: mrm/mrm_joint_controller
   action_ns: follow_joint_trajectory
   type: FollowJointTrajectory
   default: true
   joints:
     - base_link__link_01
     - link_01__link_02
     - link_02__link_03
     - link_03__grapple

 - name: mrm/gripper_controller
   action_ns: follow_joint_trajectory
   type: FollowJointTrajectory
   default: true
   joints:
     - finger_joint1
     - finger_joint2
     - finger_joint3
     - finger_joint4
     
